owner: OBK-Smart
repo: status-stranka

sites:
  - name: Hlavní stránka
    url: $URL
  - name: Komunikační API
    url: $API
  - name: Komunikační protokol
    check: "tcp-ping"
    url: $COM_IP
    port: $COM_PORT

status-website:
  cname: status.smart.obrokov.cz
  logoUrl: https://shop.obrokov.cz/images/logo.png
  name: "OBK-Smart: Status"
  introTitle: "**OBK-Smart**: Status stránka."
  navbar:
    - title: Status stránka
      href: /
    - title: Hlavní stránka
      href: https://smart.obrokov.cz