# Change these first
owner: OBK-Smart # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Hlavní stránka
    url: $URL
  - name: Komunikační API
    url: $API
  - name: Komunikační protokol
    check: "tcp-ping"
    url: $COM_IP
    port: $COM_PORT

status-website:
  cname: status.smart.obrokov.cz
  # baseUrl: /
  logoUrl: $LOGO
  name: "OBK-Smart: Status"
  introTitle: "**OBK-Smart**: Status stránka."
  #introMessage: 
  navbar:
    - title: Status stránka
      href: /
    - title: Hlavní stránka
      href: $URL

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration